(function() {
document.writeln('<table style="background:#CCCCCC;border-spacing:1px" cellspacing="1"><tbody><tr style="background:#FFFFFF"><td><p><span style="font-size: 18px;"><a href="#none" onclick="popKBS(\'11\');">KBS1</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="popKBS(\'12\');">KBS2</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/dN4\',\'_blank\'); return false;">대구MBC</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/bNq\',\'_blank\'); return false;">여수MBC</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/d7Y\',\'_blank\'); return false;">CJB</a></span></p>');
document.writeln('</td></tr>');
document.writeln('<tr style="background:#FFFFFF"><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/dGN\',\'_blank\'); return false;">TJB</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/d8a\',\'_blank\'); return false;">JTBC</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/bMV\',\'_blank\'); return false;">채널A</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'http://broadcast.tvchosun.com/onair/on.cstv\',\'_blank\'); return false;">TV조선</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="popMBN();">MBN</a></span></p>');
document.writeln('</td></tr>');
document.writeln('<tr style="background:#FFFFFF"><td><p><span style="font-size: 18px;"><a href="#none" onclick="popKBSNews();">KBS뉴스</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://www.youtube.com/embed/q9bM12ucTIY?autoplay=1\',\'_blank\'); return false;">MBC뉴스</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="popSBSNews();">SBS뉴스</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/aMR\',\'_blank\'); return false;">기상청</a></span></p>');
document.writeln('</td><td><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/dQP\',\'_blank\'); return false;">이벤트</a></span></p>');
document.writeln('</td></tr>');
document.writeln('<tr style="background:#FFFFFF"><td colspan="2" align="center"><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/dHz\',\'_blank\'); return false;">문화방송</a></span></p>');
document.writeln('</td><td colspan="3" align="center"><p><span style="font-size: 18px;"><a href="#none" onclick="window.open(\'https://xzx.kr/dH2\',\'_blank\'); return false;">서울방송</a></span></p>');
document.writeln('</td></tr>');
document.writeln('</tbody></table>');
})();